language: java
jdk: openjdk13

services:
  - postgresql

before_install:
  - psql -c 'create database telegram_bot_test;' -U postgres

# Отправлять уведомление на почту teemitze@gmail.com если сборка упала
notifications:
  email:
    recipients:
      -teemitze@gmail.com
    on_success: never # default: change
    on_failure: always # default: always