USE anna_bot;
CREATE TABLE recipes(id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255) NOT NULL UNIQUE) CHARACTER SET utf8;
CREATE TABLE ingredients(id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255) NOT NULL, recipe_id INT, CONSTRAINT recipe_id_fk FOREIGN KEY (recipe_id) REFERENCES recipes(id)) CHARACTER SET utf8;